// Generated by gencpp from file point/point.msg
// DO NOT EDIT!


#ifndef POINT_MESSAGE_POINT_H
#define POINT_MESSAGE_POINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace point
{
template <class ContainerAllocator>
struct point_
{
  typedef point_<ContainerAllocator> Type;

  point_()
    : header()
    , out_of_track()
    , x()
    , y()  {
    }
  point_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , out_of_track(_alloc)
    , x(_alloc)
    , y(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _out_of_track_type;
  _out_of_track_type out_of_track;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _x_type;
  _x_type x;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::point::point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::point::point_<ContainerAllocator> const> ConstPtr;

}; // struct point_

typedef ::point::point_<std::allocator<void> > point;

typedef boost::shared_ptr< ::point::point > pointPtr;
typedef boost::shared_ptr< ::point::point const> pointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::point::point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::point::point_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::point::point_<ContainerAllocator1> & lhs, const ::point::point_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.out_of_track == rhs.out_of_track &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::point::point_<ContainerAllocator1> & lhs, const ::point::point_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace point

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::point::point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::point::point_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::point::point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::point::point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point::point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point::point_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::point::point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7739175ded79f351deb9a2f8b5da48ef";
  }

  static const char* value(const ::point::point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7739175ded79f351ULL;
  static const uint64_t static_value2 = 0xdeb9a2f8b5da48efULL;
};

template<class ContainerAllocator>
struct DataType< ::point::point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "point/point";
  }

  static const char* value(const ::point::point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::point::point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool[] out_of_track\n"
"float32[] x\n"
"float32[] y\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::point::point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::point::point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.out_of_track);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::point::point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::point::point_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "out_of_track[]" << std::endl;
    for (size_t i = 0; i < v.out_of_track.size(); ++i)
    {
      s << indent << "  out_of_track[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.out_of_track[i]);
    }
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // POINT_MESSAGE_POINT_H
